# Generated by Django 2.2.10 on 2020-09-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
