# Generated by Django 2.2.10 on 2020-09-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.IntegerField()),
                ('vendor', models.IntegerField()),
                ('clearing_date', models.DateField()),
                ('clearing_document', models.IntegerField(default=0)),
                ('assignment', models.CharField(max_length=30)),
                ('fiscal_year', models.IntegerField()),
                ('document_number', models.IntegerField()),
                ('line_item', models.IntegerField()),
                ('posting_date', models.DateField()),
                ('document_date', models.DateField()),
                ('entry_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('reference', models.CharField(max_length=30)),
                ('document_type', models.CharField(max_length=2)),
                ('posting_period', models.IntegerField()),
                ('debit_credit_ind', models.CharField(max_length=1)),
                ('trade_code', models.CharField(max_length=1)),
                ('amount_in_lc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('baseline_payment_date', models.DateField()),
                ('terms_of_payment', models.CharField(max_length=10)),
                ('payment_method', models.CharField(max_length=1)),
                ('invoice_reference', models.CharField(max_length=30)),
                ('run_date', models.DateField()),
                ('run_id', models.CharField(max_length=4)),
                ('value_date', models.DateField()),
                ('check', models.CharField(max_length=10)),
                ('paid_check', models.CharField(max_length=10)),
                ('check_encashment_date', models.DateField()),
                ('check_void_reason_code', models.CharField(max_length=10)),
                ('voided_check_date', models.DateField()),
                ('reverse_clearing', models.CharField(max_length=10)),
                ('create_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
        ),
    ]
