# Generated by Django 2.2.10 on 2020-09-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_invoice_posting_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_code',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
