# Generated by Django 2.2.10 on 2020-09-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_invoice_tax_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='baseline_payment_date',
            new_name='baseline_payment_dte',
        ),
    ]
