# Generated by Django 2.2.10 on 2020-09-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200912_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='check',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='check_void_reason_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_reference',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_check',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reverse_clearing',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='run_id',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='trade_code',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
