# Generated by Django 2.2.10 on 2020-09-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200912_0950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
