# Generated by Django 2.2.10 on 2020-09-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.IntegerField()),
                ('country', models.CharField(max_length=2)),
                ('Name', models.CharField(max_length=35)),
                ('District', models.CharField(max_length=35)),
                ('PO_Box', models.CharField(max_length=10)),
                ('PO_Box_Postal_Code', models.CharField(max_length=10)),
                ('Postal_Code', models.CharField(max_length=10)),
                ('Region', models.CharField(max_length=10)),
                ('Search_term', models.CharField(max_length=10)),
                ('Street', models.CharField(max_length=35)),
                ('Address', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=35)),
                ('Created_on', models.CharField(max_length=8)),
                ('Created_by', models.CharField(max_length=12)),
                ('Account_group', models.CharField(max_length=4)),
                ('Language_Key', models.CharField(max_length=2)),
                ('Tax_Number_1', models.CharField(max_length=16)),
                ('Tax_Number_2', models.CharField(max_length=16)),
                ('Telephone_1', models.CharField(max_length=15)),
                ('Telephone_2', models.CharField(max_length=15)),
                ('Fax_Number', models.CharField(max_length=31)),
                ('Tax_Jurisdiction', models.CharField(max_length=35)),
                ('Email', models.CharField(max_length=241)),
                ('create_date', models.CharField(max_length=20, null=True)),
                ('update_date', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
