# Generated by Django 2.2.10 on 2020-09-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='Name',
            new_name='Name_1',
        ),
        migrations.AddField(
            model_name='vendor',
            name='Name_2',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
