# Generated by Django 2.2.10 on 2020-09-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200912_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='clearing_date',
            field=models.CharField(max_length=10),
        ),
    ]
